/*
 * queueservice
 *
 * Video queue service
 *
 * API version: 0.0.1
 * Contact: sbirudavolu@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := openapi.NewDefaultApiService()
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	QueueApiService := openapi.NewQueueApiService()
	QueueApiController := openapi.NewQueueApiController(QueueApiService)

	router := openapi.NewRouter(DefaultApiController, QueueApiController)

	log.Fatal(http.ListenAndServe(":9090", router))
}
