/*
 * queueservice
 *
 * Video queue service
 *
 * API version: 0.0.1
 * Contact: sbirudavolu@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// QueueApiService is a service that implents the logic for the QueueApiServicer
// This service should implement the business logic for every endpoint for the QueueApi API.
// Include any external packages or services that will be required by this service.
type QueueApiService struct {
}

// NewQueueApiService creates a default api service
func NewQueueApiService() QueueApiServicer {
	return &QueueApiService{}
}

// AddVideo - Add video to the queue
func (s *QueueApiService) AddVideo(code string) (interface{}, error) {
	// Add api_queue_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	result := Video{Id: "3", Url: "https://youtu.be/NEwcO0QwPAk", AddedAt: time.Now()}
	return result, nil
}
