/*
 * queueservice
 *
 * Video queue service
 *
 * API version: 0.0.1
 * Contact: sbirudavolu@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	db *Database
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService(db *Database) DefaultApiServicer {
	return &DefaultApiService{db: db}
}

// GetQueue -
func (s *DefaultApiService) GetQueue(code string) (interface{}, error) {
	result, err := s.db.GetVideoQueue(code)
	if err != nil {
		return VideoQueue{Room: code}, nil
	}
	return result, nil
}
