/*
 * queueservice
 *
 * Video queue service
 *
 * API version: 0.0.1
 * Contact: sbirudavolu@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A QueueApiController binds http requests to an api service and writes the service results to the http response
type QueueApiController struct {
	service QueueApiServicer
}

// NewQueueApiController creates a default api controller
func NewQueueApiController(s QueueApiServicer) Router {
	return &QueueApiController{service: s}
}

// Routes returns all of the api route for the QueueApiController
func (c *QueueApiController) Routes() Routes {
	return Routes{
		{
			"AddVideo",
			strings.ToUpper("Post"),
			"/v1/queue/{code}/add",
			c.AddVideo,
		},
	}
}

// AddVideo - Add video to the queue
func (c *QueueApiController) AddVideo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	code := params["code"]
	result, err := c.service.AddVideo(code)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
