/*
 * queueservice
 *
 * Video queue service
 *
 * API version: 0.0.1
 * Contact: sbirudavolu@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// VideoQueue - Queue of videos
type VideoQueue struct {

	Queue []Video `json:"queue,omitempty"`

	LastEdited time.Time `json:"lastEdited,omitempty"`
}
