/*
 * queueservice
 *
 * Video queue service
 *
 * API version: 0.0.1
 * Contact: sbirudavolu@umass.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AddVideoRequest - Video request
type AddVideoRequest struct {

	Url string `json:"url,omitempty"`
}
